MJSEC-MJU/MSG_CTF_BACK

nginx/nginx.conf
=> feat: nginx 백엔드 경로 /api/로 수정

nginx/nginx.conf
=> nginx: /api/ 경로 nginx cors 설정

nginx/nginx.conf
fix: frontend 라우팅 문제 해결-index.html로 반환
nginx 설정을 수정했습니다
=> fix: frontend 라우팅 문제 해결-index.html로 반환

nginx/nginx.conf
=> fix: frontend 라우팅 문제 해결-frontend로 반환

Back/src/main/java/com/mjsec/ctf/security/JwtFilter.java
=> fix: jwt 검증 필터링 통과 추가

nginx/nginx.conf
제가 봤을 떄 nginx 버퍼링 걸려서 nginx 설정 추가해보았습니다
=> add: proxy_buffering off,proxy_cache off

nginx/nginx.conf
=> feat/nginx Authorization proxy_set_header 추가

.github/workflows/backend-cd.yml
=> cd: redis docker-compose 실행구문 추가

Back/src/main/resources/application-local.yml
=> fix: 환경변수 명 오탈자

Back/src/main/resources/application-local.yml, exploit.py
=> fix: redis 환경변수명 변경

Back/src/main/java/com/mjsec/ctf/config/RedisConfig.java, Back/src/main/resources/application-local.yml
=> fix(redis config): RedisConnectionFactory 추가

Back/src/main/java/com/mjsec/ctf/controller/AdminController.java
api/admin/validate 구현완료
```
login_url = "http://127.0.0.1:8080/api/users/sign-in"
admin_credentials = {
"loginId": "admin",
"password": "admin_pass"      # 관리자 비밀번호 (실제 값으로 대체)
}
login_response = requests.post(login_url, json=admin_credentials)
if login_response.status_code != 200:
print("관리자 로그인 실패:", login_response.text)
exit()
login_data = login_response.json()
access_token = login_data.get("accessToken")
print("Access Token:", access_token)
validate_url = "http://127.0.0.1:8080/api/admin/validate"
headers = {
"Authorization": "Bearer " + access_token,
"Content-Type": "application/json"
}
validate_response = requests.get(validate_url, headers=headers)
print("Validate response code:", validate_response.status_code)
print("Validate response text:", validate_response.text) …
```
=> feat: api/admin/validate 구현완료

Back/src/main/java/com/mjsec/ctf/controller/AdminController.java, Back/src/main/java/com/mjsec/ctf/service/UserService.java
feat: api/admin/member/{user_id} api 구현 완료
```
login_url = "http://127.0.0.1:8080/api/users/sign-in"
admin_credentials = {
"loginId": "admin",         # 관리자 로그인 아이디 (실제 값으로 대체)
"password": "admin_pass"      # 관리자 비밀번호 (실제 값으로 대체)
}
login_response = requests.post(login_url, json=admin_credentials)
if login_response.status_code != 200:
print("관리자 로그인 실패:", login_response.text)
exit()
login_data = login_response.json()
access_token = login_data.get("accessToken")
print("Access Token:", access_token)
user_id=4
admin_url = f"http://127.0.0.1:8080/api/admin/member/{user_id}"
headers = {
"Authorization": "Bearer " + access_token,
"Content-Type": "application/json"
}
user_response = requests.get(admin_url, headers=headers)
print("Admin GET status code:", user_response.status_code) …
```
=> feat: api/admin/member/{user_id} api 구현 완료

.github/workflows/backend-cd.yml, .github/workflows/ci-cd.yml, docker-compose.yml
=> feat add dicordbot API env add

.github/workflows/ci-cd.yml, Back/src/main/java/com/mjsec/ctf/controller/ChallengeController.java, Back/src/main/java/com/mjsec/ctf/service/ChallengeService.java, Back/src/main/java/com/mjsec/ctf/service/FileService.java, Back/src/main/java/com/mjsec/ctf/type/ErrorCode.java
feat: downloadfile 구현인데 한 번 확인해주세요
=> feat: downloadfile

Back/src/main/java/com/mjsec/ctf/config/SecurityConfig.java
fix: challenges 하위 경로 로그인한 경우에만 접근하게 설정
=> fix: challenges 하위 경로 로그인한 경우에만 접근하게 설정

Back/src/main/java/com/mjsec/ctf/config/AdminUserInitializer.java, Back/src/main/java/com/mjsec/ctf/jwt/CustomLoginFilter.java, Back/src/main/java/com/mjsec/ctf/service/UserService.java
feat: role 역할 ROLE_ 접두사 추가 및 대문자 통일
=> feat: role 역할 ROLE_ 접두사 추가 및 대문자 통일

Back/src/main/java/com/mjsec/ctf/config/SecurityConfig.java
SecurityConfig에서 SessionManagement 삭제
=> SessionManagement 삭제

Back/src/main/java/com/mjsec/ctf/config/SecurityConfig.java
=> Fix:JWTFilter 수정

Back/src/main/java/com/mjsec/ctf/dto/ChallengeDto.java
=> Fix: 전체 문제 정보 반환 수정

Back/src/main/java/com/mjsec/ctf/domain/ChallengeEntity.java, Back/src/main/java/com/mjsec/ctf/service/ChallengeService.java, Back/src/main/resources/application-local.yml
feat(submit): add first blood sender
=> feat(submit): add first blood sender

.github/workflows/backend-cd.yml, docker-compose.yml
feat: cd,docker-compose api_url 환경변수 추가
=> feat: cd,docker-compose api_url 환경변수 추가

Back/src/main/java/com/mjsec/ctf/service/ChallengeService.java
=> feat(submit): add flag null check

Back/src/main/java/com/mjsec/ctf/config/SecurityConfig.java, Back/src/main/java/com/mjsec/ctf/dto/ChallengeDto.java, Back/src/main/java/com/mjsec/ctf/service/ChallengeService.java
feat(submit): fixed string compare
=> feat(submit): fixed string compare

Back/src/main/java/com/mjsec/ctf/controller/UserController.java, Back/src/main/java/com/mjsec/ctf/dto/ChallengeDto.java, Back/src/main/java/com/mjsec/ctf/repository/BlacklistedTokenRepository.java, Back/src/main/java/com/mjsec/ctf/repository/HistoryRepository.java, Back/src/main/java/com/mjsec/ctf/service/UserService.java
=> 수정 (단국대 -> 건국대 이메일 인증)

Back/src/main/java/com/mjsec/ctf/controller/AdminChallengeController.java, Back/src/main/java/com/mjsec/ctf/controller/ChallengeController.java, Back/src/main/java/com/mjsec/ctf/domain/ChallengeEntity.java, Back/src/main/java/com/mjsec/ctf/dto/ChallengeDto.java, Back/src/main/java/com/mjsec/ctf/service/ChallengeService.java, Back/src/main/java/com/mjsec/ctf/type/ChallengeCategory.java
문제 카테고리 추가했습니다!!
만약에 카테고리를 추가 안한다? 
그러면 기본값 MISC로 해놓았습니당
=> feat: 문제 카테고리 추가

Back/src/main/java/com/mjsec/ctf/dto/ChallengeDto.java
=> fix: 문제 카테고리 null 값 처리

Back/src/main/java/com/mjsec/ctf/service/ChallengeService.java
- 커밋메시지를 잘못썼습니다... submit 메소드가 아닌 afterSubmit 메소드 내에서 updateLeaderboard 메소드를 호출하도록 하였습니다.
- afterSubmit 내부에서 유저에 대한 히스토리 리스트를 반복문으로 돌며 가장 늦은 제출 시각을 저장하도록 하였습니다.
- afterSubmit 메소드가 끝나기 전에 updateLeaderboard 메소드를 호출하도록 하였습니다.
- Postman 테스트
=> fix(challenge service): add update-leaderboard logic in afterSubmit method

Back/src/main/java/com/mjsec/ctf/service/UserService.java
- HistoryDto를 return 해줄 때 challengeId를 반환했어야 했는데 userId를 반환했습니다,,,
- 밤을 새고 올려서 잠시 정신이 나갔던 것 같습니다,,,
=> fix/get challenge history: fixed return value in dto

Back/src/main/java/com/mjsec/ctf/service/UserService.java
fix: profile에 loginId 값 추가하였습니다.
=> fix: profile에 loginId 값 추가

Back/src/main/java/com/mjsec/ctf/entity/Leaderboard.java, Back/src/main/java/com/mjsec/ctf/repository/LeaderboardRepository.java, Back/src/main/java/com/mjsec/ctf/service/ChallengeService.java, Back/src/main/java/com/mjsec/ctf/service/LeaderboardService.java, Back/src/main/java/com/mjsec/ctf/service/UserService.java, Back/src/main/resources/templates/leaderboard.html
Leaderboard.java에 있던 user_id 수정 + 혹시 몰라서 LeaderRepository에 있는 userid 대신 userId 로 수정
user profile 에서 user_id 대신 userId 로 수정
=> Fix: user_id -> userId로 통일

Back/src/main/java/com/mjsec/ctf/service/ChallengeService.java
flag를 Spring Security의 BCryptPasswordEncoder로 암호화해서 저장하고 검증도 hash로 인코딩해서 비교하는 식으로 검증이 이뤄집니다.
=> fix: flag 암호화

Back/src/main/java/com/mjsec/ctf/controller/LeaderboardController.java, Back/src/main/java/com/mjsec/ctf/filter/CustomLoginFilter.java, Back/src/main/java/com/mjsec/ctf/filter/CustomLogoutFilter.java, Back/src/main/java/com/mjsec/ctf/filter/JwtFilter.java
=> fix-jwtauth error send

Back/build.gradle, Back/src/main/java/com/mjsec/ctf/config/RedisConfig.java, Back/src/main/java/com/mjsec/ctf/service/ChallengeService.java, Back/src/main/java/com/mjsec/ctf/service/JwtService.java
- build.gradle에 의존성 추가
- RedisConfig에 최대 연결 수와 최소 유휴 연결 수를 설정
- ChallengeService 코드 내부 submit 메소드에 Redisson을 활용한 락 기능 추가(제출한 기록이 없고 정답 문자열이 맞을 때)
=> fix(submit): add Redisson for concurrency control

Back/src/main/java/com/mjsec/ctf/service/ChallengeService.java
- submit 내부 전체 로직에 대해 락을 걸어서 동시성을 제어합니다.
=> fix(submit): add lock for concurrency control

Back/src/main/java/com/mjsec/ctf/repository/SubmissionRepository.java, Back/src/main/java/com/mjsec/ctf/service/ChallengeService.java
- Submission 레포지토리 내에 적용했던 락 제거
- 동시성 제어를 위해 Submit 메소드 내부에서 이중 Lock 적용
=> fix(submit): remove lock annotation from submission repository and apply double lock to submit method

Back/src/main/java/com/mjsec/ctf/config/FilterConfig.java, Back/src/main/java/com/mjsec/ctf/filter/AccessControlFilter.java
=> fix(filter): removed annotation

Back/src/main/java/com/mjsec/ctf/config/FilterConfig.java, Back/src/main/java/com/mjsec/ctf/filter/AccessControlFilter.java
=> fix(filter): add annotation

Back/src/main/java/com/mjsec/ctf/filter/CustomLoginFilter.java
=> fix(reissue): fixed expiry ms

Back/src/main/java/com/mjsec/ctf/filter/JwtFilter.java
=> fix(reissue): fixed error code

Back/src/main/java/com/mjsec/ctf/controller/ReissueController.java, Back/src/main/java/com/mjsec/ctf/filter/CustomLoginFilter.java
=> fix(reissue): fixed expiredMs

Back/src/main/java/com/mjsec/ctf/config/FilterConfig.java
=> fix(access): fixed start time and end time

nginx/nginx.conf
=> fix: nginx file size

Back/src/main/java/com/mjsec/ctf/config/GlobalCorsConfig.java, Back/src/main/java/com/mjsec/ctf/config/SecurityConfig.java, Back/src/main/resources/application-local.yml
=> Fix: CORS 하드코딩 버전

Back/src/main/java/com/mjsec/ctf/filter/JwtFilter.java
=> JwtFilter OPTIONS 우회
