- Back/.gitattributes
- Back/.gitignore
- Back/src/main/java/com/mjsec/ctf/CtfApplication.java
- Back/src/main/java/com/mjsec/ctf/config/PasswordEncoderConfig.java
- Back/src/main/java/com/mjsec/ctf/config/SecurityConfig.java
- Back/src/main/java/com/mjsec/ctf/config/SwaggerConfig.java
- Back/src/main/java/com/mjsec/ctf/domain/BaseEntity.java
- Back/src/main/java/com/mjsec/ctf/dto/ErrorResponse.java
- Back/src/main/java/com/mjsec/ctf/dto/SuccessResponse.java
- Back/src/main/java/com/mjsec/ctf/exception/GlobalExceptionHandler.java
- Back/src/main/java/com/mjsec/ctf/exception/RestApiException.java
- Back/src/main/java/com/mjsec/ctf/security/JwtFilter.java
- Back/src/main/java/com/mjsec/ctf/service/JwtService.java
- Back/src/main/java/com/mjsec/ctf/type/ErrorCode.java
- Back/src/main/java/com/mjsec/ctf/type/ResponseMessage.java
- Back/src/main/java/com/mjsec/ctf/type/UserRole.java
- Back/src/main/resources/application-local.yml
- 대부분의 스프링부트 프로젝트에 적용할 수 있는 기본 설정 파일, Basic 클래스, Basic enum 파일들을 추가
Config 패키지
- PasswordEncoderConfig : Spring Security에서 비밀번호 암호화를 위해 PasswordEncoder를 설정(BCryptPasswordEncoder를 return)
- SecurityConfig : 기본적인 Spring Security 설정을 포함, 인증 및 권한 관리 로직등을 정의(Spring Security 필터체인 커스터마이징)
- SwaggerConfig : API 문서화를 위해 Swagger를 설정(프로젝트의 REST API를 시각화된 UI로 확인할 수 있게 해줌)
Domain 패키지
- BaseEntity : 공통 엔티티 클래스(최상위 엔티티 클래스이며 주로 모든 엔티티에서 공통으로 사용하는 필드(예: createdAt, updatedAt)를 정의)
Dto(Data Transfer Object) 패키지
- ErrorResponse : 예외 발생 시 반환할 표준화된 에러 응답 형식을 정의
- SuccessResponse : 요청이 성공했을 때 반환할 표준화된 응답 형식을 정의
Exception 패키지
- GlobalExceptionHandler : 애플리케이션 전역에서 발생하는 예외를 처리, 예외에 따라 적절한 응답을 반환
- RestApiException : REST API에서 발생하는 예외를 세부적으로 정의
Security 패키지
- JwtFilter : JWT 토큰을 검증하고, 인증 정보가 포함된 요청을 처리하는 필터를 구현 …
> chore(config): add config files and basic settings

- Back/src/main/java/com/mjsec/ctf/config/AdminUserInitializer.java
- Back/src/main/java/com/mjsec/ctf/config/SecurityConfig.java
- Back/src/main/java/com/mjsec/ctf/controller/AdminController.java
- Back/src/main/java/com/mjsec/ctf/dto/USER/UserDTO.java
- Back/src/main/java/com/mjsec/ctf/jwt/CustomLoginFilter.java
- Back/src/main/java/com/mjsec/ctf/service/UserService.java
- Back/src/main/java/com/mjsec/ctf/type/ResponseMessage.java
- Back/src/main/resources/application.properties
- docker-compose-backend-local.yml
- /api/admin/change/member/{userId} 엔드포인트 구현 (PUT)
- UserDTO에 Update 용 DTO 추가하여 이메일, 대학, 로그인 아이디, 비밀번호 변경 지원
- UserService에 updateMember 메서드 추가 (비밀번호 암호화 포함)
- AdminController 구현 및 @PreAuthorize("hasRole('ADMIN')") 적용
- JWT 생성 로직 수정: 관리자인 경우 "ROLE_ADMIN" 접두사 포함
- SecurityConfig 업데이트: /api/admin/** 경로에 관리자 권한 적용
관리자 계정 초기화 및 관련 보안 설정도 함께 적용함.
```
login_url = "http://localhost:8080/api/users/sign-in"
login_data = {
"loginId": "admin",         
"password": "admin_pass"    
}
login_response = requests.post(login_url, json=login_data)
print("로그인 상태 코드:", login_response.status_code)
if login_response.status_code == 200:
login_json = login_response.json()
access_token = login_json.get("accessToken")
if not access_token:
print("accessToken이 응답에 없습니다.")
exit(1)
print("발급받은 …
```
> feat:관리자계정 추가 및 회원정보 update API 추가

- Back/src/main/java/com/mjsec/ctf/config/GlobalCorsConfig.java
config.setAllowedOriginPatterns(Arrays.asList("http://localhost", "https://msg.mjsec.kr"));
config.setAllowCredentials(true);
config.addAllowedHeader("*");
config.addAllowedMethod("*");
이렇게 로컬이랑 실제 도메인에서 적용되게 해보았습니다
> add: cors 정책

- Back/src/main/java/com/mjsec/ctf/controller/AdminController.java
- Back/src/main/java/com/mjsec/ctf/service/UserService.java
- Back/src/main/java/com/mjsec/ctf/type/ResponseMessage.java
사용자 계정을 삭제하는 api를 만들었습니다.
삭제 TEST
[현 유저테이블]
여기서 user_id 8을 지워보기
```
login_url = "http://localhost:8080/api/users/sign-in"
login_data = {
"loginId": "huhuh",         # 관리자 계정 ID
"password": "TestPass123!"      # 관리자 비밀번호
}
login_response = requests.post(login_url, json=login_data)
print("로그인 상태 코드:", login_response.status_code)
if login_response.status_code == 200:
login_json = login_response.json()
access_token = login_json.get("accessToken")
if not access_token:
print("accessToken이 응답에 없습니다.")
exit(1)
print("발급받은 accessToken:", access_token)
else:
print("로그인 실패:", login_response.text)
exit(1)
user_id = 8
delete_url = f"http://localhost:8080/api/admin/delete/member/{user_id}"
headers = {
"Authorization": "Bearer " + access_token
}
delete_response = …
```
> feat: delete/member api

- Back/src/main/java/com/mjsec/ctf/controller/AdminChallengeController.java
feat: api/admin/challenge/summary 구현완료
```
import os
from dotenv import load_dotenv
load_dotenv()
base_url = "http://localhost:8080"
login_url = f"{base_url}/api/users/sign-in"
admin_challenge_url = f"{base_url}/api/admin/challenge/summary"
admin_credentials = {
"loginId": "admin",
"password": "admin_pass"
}
login_response = requests.post(login_url, json=admin_credentials)
print("Login status code:", login_response.status_code)
if login_response.status_code == 200:
login_data = login_response.json()
admin_token = login_data.get("accessToken")
print("Admin access token:", admin_token)
headers = {
"Authorization": f"Bearer {admin_token}",
"Content-Type": "application/json"
}
challenge_response = requests.get(admin_challenge_url, headers=headers)
print("Admin Challenge API …
```
> feat: api/admin/challenge/summary 구현완료

- Back/src/main/java/com/mjsec/ctf/controller/AdminChallengeController.java
```
import os
from dotenv import load_dotenv
load_dotenv()
BASE_URL = "http://localhost:8080"
LOGIN_URL = f"{BASE_URL}/api/users/sign-in"
CHALLENGE_DETAIL_URL = f"{BASE_URL}/api/admin/challenge/1"
admin_credentials = {
"loginId": "admin",
"password": "admin_pass"
}
login_response = requests.post(LOGIN_URL, json=admin_credentials)
print("Login status code:", login_response.status_code)
if login_response.status_code == 200:
login_data = login_response.json()
admin_token = login_data.get("accessToken")
print("Admin access token:", admin_token)
else:
print("Login failed:", login_response.text)
exit()
headers = {
"Authorization": f"Bearer {admin_token}",
"Content-Type": "application/json"
}
challenge_response = requests.get(CHALLENGE_DETAIL_URL, headers=headers) …
```
> feat: api/admin/challenge/{challenge_id} api 구현완료

- Back/src/main/java/com/mjsec/ctf/controller/UserController.java
- Back/src/main/java/com/mjsec/ctf/dto/USER/UserDTO.java
- Back/src/main/java/com/mjsec/ctf/service/UserService.java
- Back/src/main/java/com/mjsec/ctf/type/ErrorCode.java
회원가입/ 이메일 확인/ 아이디 확인시 에러 코드들 추가
프론트에 맞춰서 한다고는 노력했습니다요 ...
```
INVALID_ID_LENGTH_MIN(HttpStatus.BAD_REQUEST, "로그인 아이디는 최소 4자 이상이어야 합니다."),
INVALID_ID_LENGTH_MAX(HttpStatus.BAD_REQUEST, "로그인 아이디는 20자 이하로 입력해주세요."),
INVALID_ID_CHARACTERS(HttpStatus.BAD_REQUEST, "로그인 아이디는 영문과 숫자만 사용할 수 있습니다."),
INVALID_ID_WHITESPACE(HttpStatus.BAD_REQUEST, "로그인 아이디에 공백을 포함할 수 없습니다."),
EMPTY_EMAIL(HttpStatus.BAD_REQUEST, "이메일을 입력해주세요."),
EMPTY_PASSWORD(HttpStatus.BAD_REQUEST, "비밀번호를 입력해주세요."),
INVALID_PASSWORD_LENGTH_MIN(HttpStatus.BAD_REQUEST, "비밀번호는 최소 8자 이상이어야 합니다."),
INVALID_PASSWORD_LENGTH_MAX(HttpStatus.BAD_REQUEST, "비밀번호는 32자 이하로 입력해주세요."),
INVALID_PASSWORD_WHITESPACE(HttpStatus.BAD_REQUEST, "비밀번호에 공백을 포함할 수 없습니다."),
INVALID_PASSWORD_FORMAT(HttpStatus.BAD_REQUEST, "비밀번호는 소문자, 대문자, 숫자 및 특수문자(!@#$%^&*)를 …
```
> 회원가입/ 이메일 확인/ 아이디 확인시 에러 코드들 추가

- Back/src/main/java/com/mjsec/ctf/domain/HistoryEntity.java
- Back/src/main/java/com/mjsec/ctf/dto/HistoryDto.java
- Back/src/main/java/com/mjsec/ctf/service/HistoryService.java
/graph 엔드포인트에 사용되는
History Entity, Dto, Service 에 univ 추가하였습니다.
/graph 엔드포인트 sse 통신 응답값에 univ 포함됩니다.
대학별 합산 점수는 프론트에서 univ 분류로 계산 가능합니다.
> feat: History Entity, Dto, Service 에 univ 필드 추가하여 응답값에 포함

- Back/src/main/java/com/mjsec/ctf/controller/UserController.java
- Back/src/main/java/com/mjsec/ctf/domain/ChallengeEntity.java
- Back/src/main/java/com/mjsec/ctf/dto/HistoryDto.java
- Back/src/main/java/com/mjsec/ctf/service/ChallengeService.java
- Back/src/main/java/com/mjsec/ctf/service/HistoryService.java
- Back/src/main/java/com/mjsec/ctf/service/UserService.java
- Back/src/main/java/com/mjsec/ctf/type/ResponseMessage.java
- 프로필 조회 api에서 사용하는 UserService.getProfile 메서드 내에서 히스토리를 제외한 값들을 반환하도록 변경하였습니다.
- 히스토리 조회를 위해 히스토리 Dto에 문제 제목(title)을 추가하였습니다.
- ResponseMessage에 GET_HISTORY_SUCCESS("히스토리 조회 성공") 를 추가하였습니다.
- /api/users/challenges(유저가 푼 문제 리스트 조회 (히스토리)) 를 위해 컨트롤러와 서비스 레이어에 메서드를 추가하였습니다.
토큰 검증이 이루어지고 레포지토리에서 유저를 불러옵니다.
> Feature/solved : add /api/users/challenges api for get list of history what user solved

- Back/src/main/java/com/mjsec/ctf/domain/HistoryEntity.java
univ 값이 null 로 넘어오는 상황 확인하였습니다.
서버 DB 의 컬럼명과 매핑되지 않아 생기는 문제라고 파악되어
@Column(name = "univ")
추가하여 univ 컬럼과 historyEntity 의 univ 매핑시켰습니다.
> feat: add univ Column mapping

- Back/src/main/java/com/mjsec/ctf/service/ChallengeService.java
challenge service에서 univ정보가 전달이 안돼서 null로 표시되는거 해결해보고자 합니다.
> feat/univ challege service 에서 univ정보도 전달

- Back/src/main/java/com/mjsec/ctf/repository/HistoryRepository.java
- Back/src/main/java/com/mjsec/ctf/service/ChallengeService.java
- Back/src/main/java/com/mjsec/ctf/service/UserService.java
Problem 삭제할 때 해당 삭제하는 challenge_id 랑 같은 제출기록을 제거하기 위해 histroy 엔티티에서도 삭제처리하여 엔티티 간 연관 관계 추가했습니다.
> feat: Problem 삭제시 history 엔티티도 제거

- Back/src/main/java/com/mjsec/ctf/dto/ChallengeDto.java
- Back/src/main/java/com/mjsec/ctf/service/ChallengeService.java
- ChallengeDto : 사용자가 모든 문제 리스트를 조회할 때 정답 처리된 문제는 true로, 풀지 않은 문제는 false라는 값을 반환하도록 'solved'변수를 Dto에 추가하였습니다.
- ChallengeService : history 테이블에서 풀이 여부를 확인하기 위해 현재 사용자의 loginId를 반환하는 메소드를 추가하였습니다. 
- /api/challenges/all 요청을 보낼 때 access 토큰을 넣어서 보내기 때문에 토큰에서 loginId를 추출해도 되지만, SecurityContextHolder에서 도 추출이 되기에 기존 코드 변경을 최소화하였습니다.
- ChallengeService : 모든 문제를 리스트화하는 메소드에 풀이 여부를 확인하는 로직을 추가하였습니다.
- PostMan 테스트
> fix(get-all-challenges): add boolean value 'solved' in ChallengeDto.Simple

- Back/src/main/java/com/mjsec/ctf/config/FilterConfig.java
- Back/src/main/java/com/mjsec/ctf/config/SecurityConfig.java
- Back/src/main/java/com/mjsec/ctf/filter/AccessControlFilter.java
- Back/src/main/java/com/mjsec/ctf/filter/CustomLoginFilter.java
- Back/src/main/java/com/mjsec/ctf/filter/CustomLogoutFilter.java
- Back/src/main/java/com/mjsec/ctf/filter/JwtFilter.java
- FilterConfig : startTime과 endTime을 설정해두었습니다.
- AccessControlFilter : 대회 시작 전에는 /api/users/sign-up, /api/users/sign-in 에만 접근할 수 있도록 필터를 구현하였습니다.
- AccessControlFilter : 대회가 끝난 후에는 제출을 할 수 없도록 필터를 구현하였습니다.
대회시작 전에 회원가입 / 로그인 이외의 API에 접근할 경우
대회가 끝난 후에 제출을 할 경우
> feat(filter): add access control filter for ctf start time and end time

- Back/src/main/java/com/mjsec/ctf/controller/ChallengeController.java
- Back/src/main/java/com/mjsec/ctf/domain/ChallengeEntity.java
- Back/src/main/java/com/mjsec/ctf/domain/SubmissionEntity.java
- Back/src/main/java/com/mjsec/ctf/repository/SubmissionRepository.java
- Back/src/main/java/com/mjsec/ctf/service/ChallengeService.java
- Back/src/main/java/com/mjsec/ctf/type/ResponseMessage.java
Challenge 엔티티의 description, url 컬럼에 length를 설정해주었습니다.
브루트 포스를 이용한 정답 제출을 막기 위해 submission 엔티티와 레포지토리를 만들었습니다.
chllenge 서비스 코드에서 이전 제출 기록이 없는 사용자라면 submission 엔티티를 새로 만들고, 제출 횟수와 마지막 제출 시간 기준 30초가 경과하였는지 체크 후 flag에 대한 정답 여부를 판별합니다.
정답이 아니라면 제출 횟수 count를 올리고 마지막 제출 시간을 저장한 뒤에 Wrong이라는 문자열을 반환합니다.
결국 문제 제출 api 호출 시, Correct, Submitted, Wait, Wrong 총 4가지의 문자열 중 하나를 반환 받게 됩니다.
> feat(submit penalty): add submission entity and repository for brute force penalty check

- Back/src/main/java/com/mjsec/ctf/repository/UserRepository.java
- Back/src/main/java/com/mjsec/ctf/service/ChallengeService.java
- Back/src/main/java/com/mjsec/ctf/type/ErrorCode.java
ChallengeService 코드 내부의 afterSubmit 메서드의 이름을 updateTotalPoints로 바꾸었습니다.(사용자가 문제 제출을 할 떄 뿐만아니라 관리자가 문제를 삭제할 때도 사용하기 위함)
문제를 삭제시킬 때 유저 엔티티의 totalPoints와 리더보드 엔티티의 totalPoints를 업데이트 합니다.
문제를 삭제시킬 때 먼저 history와 challenge를 삭제하고 updateTotalPoints 메소드를 호출하게 됩니다.
다만 전체 사용자에 대한 점수를 업데이트 할 때 히스토리 레포지토리를 참조하기 때문에, 문제 전체가 삭제되어 남아있지 않은 경우 메서드 내부 for문으로 들어가지 못하는 문제가 있었습니다.
따라서 history 레포지토리에서 중복없이 불러온 사용자의 id 리스트가 empty라면, 모든 유저의 user 엔티티와 리더보드 엔티티의 totalPoints가 0이 되도록 설정하였습니다.
문제 삭제 후(전체 문제 삭제) user 엔티티
문제 삭제 후(전체 문제 삭제) history 엔티티
문제 삭제 후(전체 문제 삭제) leaderboard 엔티티
> fix(delete-challenge): set total points of user entity and leaderboard if challenge deleted

- Back/src/main/java/com/mjsec/ctf/controller/LeaderboardController.java
- Back/src/main/java/com/mjsec/ctf/domain/HistoryEntity.java
- Back/src/main/java/com/mjsec/ctf/domain/LeaderboardEntity.java
- Back/src/main/java/com/mjsec/ctf/filter/JwtFilter.java
- Back/src/main/java/com/mjsec/ctf/repository/LeaderboardRepository.java
- Back/src/main/java/com/mjsec/ctf/repository/SubmissionRepository.java
- Back/src/main/java/com/mjsec/ctf/service/ChallengeService.java
- Back/src/main/java/com/mjsec/ctf/service/JwtService.java
- Back/src/main/java/com/mjsec/ctf/service/LeaderboardService.java
- Back/src/main/resources/templates/leaderboard.html
- jwt 토큰을 재발급할 때 프론트로 json 데이터를 넘겨주게 됩니다.(access 토큰, refresh 토큰)
- 동시성 문제를 제어하기 위해 SubmissionEntityRepository에 Lock 기능을 추가하였습니다.
> fix: jwt reissue, submission

- Back/src/main/java/com/mjsec/ctf/repository/HistoryRepository.java
- Back/src/main/java/com/mjsec/ctf/service/ChallengeService.java
- 동시성 문제 해결을 위해 history 레포지토리 내부에서 비관적 락을 사용하여 히스토리를 조회합니다.
- 이전에는 제출 시도가 3회 이상이면 30초 대기를 걸었지만, 2회로 줄였습니다.(동시성과는 별도의 이슈)
> fix(submit): add pessimistic lock in history repository

- Back/build.gradle
- Back/src/main/java/com/mjsec/ctf/controller/ReissueController.java
- Back/src/main/java/com/mjsec/ctf/filter/JwtFilter.java
- Back/src/main/java/com/mjsec/ctf/service/JwtService.java
- 백에서 자동적으로 토큰을 재발급하는 방식이 아닌, ReissueController를 사용하여 만료 토큰에 대한 재발급을 진행합니다.
- 토큰 만료시 401에러와 함께 "Access token expired"라는 에러 문자열을 반환합니다.
> fix(reissue): add reissue controller

- Back/build.gradle
- Back/src/main/java/com/mjsec/ctf/controller/LeaderboardController.java
- Back/src/main/java/com/mjsec/ctf/controller/UserController.java
- Back/src/main/java/com/mjsec/ctf/domain/HistoryEntity.java
- Back/src/main/java/com/mjsec/ctf/domain/LeaderboardEntity.java
- Back/src/main/java/com/mjsec/ctf/domain/RefreshEntity.java
- Back/src/main/java/com/mjsec/ctf/domain/SubmissionEntity.java
- Back/src/main/java/com/mjsec/ctf/domain/UserEntity.java
- Back/src/main/java/com/mjsec/ctf/repository/HistoryRepository.java
- Back/src/main/java/com/mjsec/ctf/service/ChallengeService.java
- Back/src/main/java/com/mjsec/ctf/service/HistoryService.java
- Back/src/main/java/com/mjsec/ctf/service/UserService.java
- Back/src/main/resources/application-local.yml
User 삭제했을 때를 기준으로 자동으로 함께 삭제되는 경우를 ‘강한 의존성’ 으로 잡고,
반대로 User 삭제해도 loginId를 NULL 처리하는 방식으로 일단 데이터를 남기는 걸 ‘약한 의존성’으로 잡음.
강한 의존성
- LeaderboardEntity
- SubmissionEntity
- RefreshEntity
각각 Entity들을 UserEntity와 연관 관계 설정함.
**UserEntity**
```jsx
package com.mjsec.ctf.domain;
import com.fasterxml.jackson.annotation.JsonIgnore;
import com.mjsec.ctf.type.UserRole;
import jakarta.persistence.*;
import lombok.*;
import org.hibernate.annotations.Fetch;
import org.hibernate.annotations.FetchMode;
import java.time.LocalDateTime;
import java.util.List;
@Entity
@Getter
@Setter
@NoArgsConstructor
@AllArgsConstructor
@Builder
public class UserEntity extends BaseEntity {
@Id
@GeneratedValue(strategy = GenerationType.IDENTITY)
private Long userId;
@Column(nullable = false, unique = true)
private String loginId; …
```
> Feat: 강한 의존성, 약한 의존성 처리하기

- Back/src/main/java/com/mjsec/ctf/config/GlobalCorsConfig.java
- Back/src/main/java/com/mjsec/ctf/config/SecurityConfig.java
- Back/src/main/resources/application-local.yml
추가 
application-local.yml
```java
cors:
allowed-origins: ${CORS_ALLOWED_ORIGINS}
```
GlobalCorsConfig.java
```java
@Configuration
public class GlobalCorsConfig {
@Value("${cors.allowed-origins}")
private String allowedOrigins;
@Bean
public CorsFilter corsFilter() {
CorsConfiguration config = new CorsConfiguration();
// 허용할 출처를 명시합니다.
List<String> origins = new ArrayList<>(Arrays.asList(allowedOrigins.split(",")));
origins.add("http://localhost:3000");
configuration.setAllowedOriginPatterns(origins);
config.setAllowCredentials(true);
config.addAllowedHeader("*");
config.addAllowedMethod("*");
UrlBasedCorsConfigurationSource source = new UrlBasedCorsConfigurationSource();
source.registerCorsConfiguration("/**", config);
return new CorsFilter(source);
}
}
``` 
SecurityConfig 중
```java …
```
> Fix: CORS 설정 (환경변수 처리)

- Back/src/main/java/com/mjsec/ctf/service/ChallengeService.java
**어드민이 플래그 제출할 경우, 히스토리에 반영되지 않고 정답 , 오답 결과만 나오도록 수정함.**
**테스트**
문제 1번에 대해 어드민이 제출할 경우
flag 값이 맞으면 성공, 아니면 실패 로만 나오도록 수정함. (기록이 남지 않음.)
히스토리 기준 `login_id ‘admin’`이 존재하지 않음.
코드 상으로는
```java
if (user.getRole() != null && user.getRole().equals("ROLE_ADMIN")) {
// Admin은 플래그 검증만 하고 점수/기록은 남기지 않음
if (passwordEncoder.matches(flag, challenge.getFlag())) {
log.info("Admin {} verified challenge {} - Correct", loginId, challengeId);
return "Correct";
} else {
log.info("Admin {} verified challenge {} - Wrong", loginId, challengeId);
return "Wrong";
}
}
```
문제 제출 중간에 이 코드만 추가함. (팀 검증하기 전 먼저 어드민인지 확인 후 맞다 틀리다만 나오도록 함)
> Feat: 어드민이 문제 flag 제출 로직 추가
